# Generated by Django 5.1 on 2024-09-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
