# Generated by Django 5.1 on 2024-09-03 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_category_subscribers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
